#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00
#PBS -l vmem=30gb

mkdir -p output

echo "making a brain mask, just in case it is needed"
time singularity exec -e docker://brainlife/fsl:5.0.9 ./run.sh

echo "processing UNI image for denoising"
singularity exec -e docker://brainlife/mcr:2020a ./compiled/mp2rage_denoiseUNI

# denoise UNI image code outputs an un-gzipped .nii file, so gzip it for forward compatability
gzip ./output/unit1.nii

if [ ! -f ./output/unit1.nii.gz ]; then
       echo "mp2rage_denoiseUNI.m didn't produce a denoised unit1.nii.gz file"
       exit 1
fi

cat << EOF > product.json
{
    "brainlife": [
        {
            "type": "image/png",
	    "name": "Original and Denoised UNIT1",
            "base64": "$(base64 -w 0 qa.png)"
        }
    ]
}
EOF

echo "all done!"
