#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:20:00
#PBS -l vmem=30gb

mkdir -p output

singularity exec -e docker://brainlife/mcr:2020a ./compiled/mp2rage_denoiseUNI

#matlab -nosplash -nodisplay -r mp2rage_denoiseUNI.m

gzip ./output/unit1.nii

if [ ! -f ./output/unit1.nii.gz ]; then
       echo "mp2rage_denoiseUNI.m didn't produce a denoised unit1.nii.gz file"
       exit 1
fi

echo "all done"

cat << EOF > product.json
{
    "brainlife": [
        {
            "type": "image/png",
	    "name": "Original and Denoised UNIT1",
            "base64": "$(base64 -w 0 qa.png)"
        }
    ]
}
EOF
